In [1]:
import pandas as pd
import os

# Verificar la ruta actual
print("Directorio actual:", os.getcwd())

# Intentar leer el archivo desde la carpeta data
DATA_PATH = '../data/'  # Esto significa "sube un nivel desde notebooks, luego entra a data"
FILE_NAME = 'accepted_2007_to_2018Q4.csv'  # Ajusta el nombre si tu archivo se llama diferente

try:
    df = pd.read_csv(DATA_PATH + FILE_NAME, low_memory=False)
    print(f"Dataset cargado exitosamente. Dimensiones: {df.shape}")
except FileNotFoundError:
    print("Error: No se encontró el archivo. Verifica el nombre y la ubicación.")

Directorio actual: C:\Users\user\Documents\lending-club-risk-analysis\notebooks
Dataset cargado exitosamente. Dimensiones: (2260701, 151)

In [4]:
# Core Libraries for Data Manipulation
import pandas as pd
import numpy as np

# Libraries for Data Visualization (for exploratory analysis)
import matplotlib.pyplot as plt
import seaborn as sns

# Libraries for Handling Dates
import datetime as dt

# Machine Learning Libraries for Advanced Imputation
from sklearn.impute import KNNImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Settings for better display
pd.set_option('display.max_columns', None) # Show all columns
pd.set_option('display.float_format', '{:.2f}'.format) # Format floats to 2 decimal places
plt.style.use('seaborn-v0_8-darkgrid') # Set a professional plot style

print("All libraries imported successfully.")

All libraries imported successfully.

In [5]:
# Define the path to your data file
DATA_PATH = '../data/' # This goes up one level from the 'notebooks' folder
FILE_NAME = 'accepted_2007_to_2018Q4.csv'  # <-- VERIFICA ESTE NOMBRE

# Load the dataset
try:
    df = pd.read_csv(DATA_PATH + FILE_NAME, low_memory=False)
    print(f"Dataset loaded successfully.")
except FileNotFoundError:
    print(f"Error: File not found at '{DATA_PATH + FILE_NAME}'. Please check the path and file name.")

# Initial Data Exploration
print(f"Initial Shape: {df.shape[0]} rows, {df.shape[1]} columns")
df.head()

Dataset loaded successfully.
Initial Shape: 2260701 rows, 151 columns

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.00,3600.00,3600.00,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.00,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.00,Aug-2003,675.00,679.00,1.00,30.00,NaN,7.00,0.00,2765.00,29.70,13.00,w,0.00,0.00,4421.72,4421.72,3600.00,821.72,0.00,0.00,0.00,Jan-2019,122.67,NaN,Mar-2019,564.00,560.00,0.00,30.00,1.00,Individual,NaN,NaN,NaN,0.00,722.00,144904.00,2.00,2.00,0.00,1.00,21.00,4981.00,36.00,3.00,3.00,722.00,34.00,9300.00,3.00,1.00,4.00,4.00,20701.00,1506.00,37.20,0.00,0.00,148.00,128.00,3.00,3.00,1.00,4.00,69.00,4.00,69.00,2.00,2.00,4.00,2.00,5.00,3.00,4.00,9.00,4.00,7.00,0.00,0.00,0.00,3.00,76.90,0.00,0.00,0.00,178050.00,7746.00,2400.00,13734.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.00,24700.00,24700.00,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.00,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,Business,577xx,SD,16.06,1.00,Dec-1999,715.00,719.00,4.00,6.00,NaN,22.00,0.00,21470.00,19.20,38.00,w,0.00,0.00,25679.66,25679.66,24700.00,979.66,0.00,0.00,0.00,Jun-2016,926.35,NaN,Mar-2019,699.00,695.00,0.00,NaN,1.00,Individual,NaN,NaN,NaN,0.00,0.00,204396.00,1.00,1.00,0.00,1.00,19.00,18005.00,73.00,2.00,3.00,6472.00,29.00,111800.00,0.00,0.00,6.00,4.00,9733.00,57830.00,27.10,0.00,0.00,113.00,192.00,2.00,2.00,4.00,2.00,NaN,0.00,6.00,0.00,5.00,5.00,13.00,17.00,6.00,20.00,27.00,5.00,22.00,0.00,0.00,0.00,2.00,97.40,7.70,0.00,0.00,314017.00,39475.00,79300.00,24667.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.00,20000.00,20000.00,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.00,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,NaN,605xx,IL,10.78,0.00,Aug-2000,695.00,699.00,0.00,NaN,NaN,6.00,0.00,7869.00,56.20,18.00,w,0.00,0.00,22705.92,22705.92,20000.00,2705.92,0.00,0.00,0.00,Jun-2017,15813.30,NaN,Mar-2019,704.00,700.00,0.00,NaN,1.00,Joint App,71000.00,13.85,Not Verified,0.00,0.00,189699.00,0.00,1.00,0.00,4.00,19.00,10827.00,73.00,0.00,2.00,2081.00,65.00,14000.00,2.00,5.00,1.00,6.00,31617.00,2737.00,55.90,0.00,0.00,125.00,184.00,14.00,14.00,5.00,101.00,NaN,10.00,NaN,0.00,2.00,3.00,2.00,4.00,6.00,4.00,7.00,3.00,6.00,0.00,0.00,0.00,0.00,100.00,50.00,0.00,0.00,218418.00,18696.00,6200.00,14877.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.00,35000.00,35000.00,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.00,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.00,Sep-2008,785.00,789.00,0.00,NaN,NaN,13.00,0.00,7802.00,11.60,17.00,w,15897.65,15897.65,31464.01,31464.01,19102.35,12361.66,0.00,0.00,0.00,Feb-2019,829.90,Apr-2019,Mar-2019,679.00,675.00,0.00,NaN,1.00,Individual,NaN,NaN,NaN,0.00,0.00,301500.00,1.00,1.00,0.00,1.00,23.00,12609.00,70.00,1.00,1.00,6987.00,45.00,67300.00,0.00,1.00,0.00,2.00,23192.00,54962.00,12.10,0.00,0.00,36.00,87.00,2.00,2.00,1.00,2.00,NaN,NaN,NaN,0.00,4.00,5.00,8.00,10.00,2.00,10.00,13.00,5.00,13.00,0.00,0.00,0.00,1.00,100.00,0.00,0.00,0.00,381215.00,52226.00,62500.00,18000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.00,10400.00,10400.00,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.00,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,major_purchase,Major purchase,174xx,PA,25.37,1.00,Jun-1998,695.00,699.00,3.00,12.00,NaN,12.00,0.00,21929.00,64.50,35.00,w,0.00,0.00,11740.50,11740.50,10400.00,1340.50,0.00,0.00,0.00,Jul-2016,10128.96,NaN,Mar-2018,704.00,700.00,0.00,NaN,1.00,Individual,NaN,NaN,NaN,0.00,0.00,331730.00,1.00,3.00,0.00,3.00,14.00,73839.00,84.00,4.00,7.00,9702.00,78.00,34000.00,2.00,1.00,3.00,10.00,27644.00,4567.00,77.50,0.00,0.00,128.00,210.00,4.00,4.00,6.00,4.00,12.00,1.00,12.00,0.00,4.00,6.00,5.00,9.00,10.00,7.00,19.00,6.00,12.00,0.00,0.00,0.00,4.00,96.60,60.00,0.00,0.00,439570.00,95768.00,20300.00,88097.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Create a copy to avoid modifying the original DataFrame directly
df_cleaned = df.copy()

# List of loan statuses considered as 'completed' with a known outcome
completed_statuses = ['Fully Paid', 'Charged Off', 'Default']

# Filter the DataFrame
df_cleaned = df_cleaned[df_cleaned['loan_status'].isin(completed_statuses)]

print(f"Shape after filtering for completed loans: {df_cleaned.shape[0]} rows")
print(f"Percentage of data retained: {df_cleaned.shape[0] / df.shape[0] * 100:.2f}%")

Shape after filtering for completed loans: 1345350 rows
Percentage of data retained: 59.51%

In [7]:
# Identify columns with more than 95% missing values
high_missing_cols = df_cleaned.columns[df_cleaned.isnull().mean() > 0.95].tolist()
print(f"Dropping {len(high_missing_cols)} columns with >95% missing values: {high_missing_cols}")

# Identify columns that are IDs or URLs (often irrelevant for modeling)
id_url_cols = ['id', 'member_id', 'url', 'desc', 'emp_title']
cols_to_drop = high_missing_cols + id_url_cols

# Drop them from our DataFrame
df_cleaned = df_cleaned.drop(columns=[col for col in cols_to_drop if col in df_cleaned.columns])
print(f"Shape after dropping irrelevant columns: {df_cleaned.shape}")

Dropping 38 columns with >95% missing values: ['member_id', 'next_pymnt_d', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog', 'hardship_type', 'hardship_reason', 'hardship_status', 'deferral_term', 'hardship_amount', 'hardship_start_date', 'hardship_end_date', 'payment_plan_start_date', 'hardship_length', 'hardship_dpd', 'hardship_loan_status', 'orig_projected_additional_accrued_interest', 'hardship_payoff_balance_amount', 'hardship_last_payment_amount', 'debt_settlement_flag_date', 'settlement_status', 'settlement_date', 'settlement_amount', 'settlement_percentage', 'settlement_term']
Shape after dropping irrelevant columns: (1345350, 109)

In [8]:
# Set a threshold (e.g., 20%)
missing_threshold = 0.20

# Find columns with missing values below the threshold
cols_to_impute = df_cleaned.columns[(df_cleaned.isnull().mean() < missing_threshold) & (df_cleaned.isnull().mean() > 0)].tolist()
cols_to_drop_high_missing = df_cleaned.columns[(df_cleaned.isnull().mean() >= missing_threshold)].tolist()

print(f"Columns to impute (missing < 20%): {len(cols_to_impute)}")
print(f"Columns to drop (missing >= 20%): {len(cols_to_drop_high_missing)}")

df_cleaned = df_cleaned.drop(columns=cols_to_drop_high_missing)
print(f"Shape after applying 80/20 rule: {df_cleaned.shape}")

Columns to impute (missing < 20%): 46
Columns to drop (missing >= 20%): 19
Shape after applying 80/20 rule: (1345350, 90)

In [9]:
# 1. Separate columns by data type
numeric_cols = df_cleaned.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = df_cleaned.select_dtypes(include=['object']).columns.tolist()

print(f"Numerical columns to impute: {len(numeric_cols)}")
print(f"Categorical columns to impute: {len(categorical_cols)}")

# 2. Impute Categorical Columns with 'Unknown'
for col in categorical_cols:
    if df_cleaned[col].isnull().any():
        df_cleaned[col] = df_cleaned[col].fillna('Unknown')

# 3. Impute Numerical Columns with KNNImputer (using a sample for speed)
# KNN can be slow on massive datasets, so we'll use a sample to fit the imputer.
sample_size = 50000 # Adjust based on your PC's performance
if len(df_cleaned) > sample_size:
    df_sample = df_cleaned[numeric_cols].sample(n=sample_size, random_state=42)
else:
    df_sample = df_cleaned[numeric_cols].copy()

print("Fitting KNNImputer on a sample...")
imputer = KNNImputer(n_neighbors=5)
imputer.fit(df_sample)

print("Applying KNNImputer to the entire dataset (this may take a few minutes)...")
# Convert to numpy array for faster transformation
df_cleaned[numeric_cols] = imputer.transform(df_cleaned[numeric_cols])

print("Imputation complete.")

Numerical columns to impute: 69
Categorical columns to impute: 21
Fitting KNNImputer on a sample...
Applying KNNImputer to the entire dataset (this may take a few minutes)...
Imputation complete.

In [10]:
# Function to cap outliers using the IQR method
def cap_outliers_iqr(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df[col] = np.where(df[col] < lower_bound, lower_bound, df[col])
    df[col] = np.where(df[col] > upper_bound, upper_bound, df[col])
    return df

# Apply capping to key financial features
cols_to_cap = ['loan_amnt', 'annual_inc', 'dti']
for col in cols_to_cap:
    if col in df_cleaned.columns:
        df_cleaned = cap_outliers_iqr(df_cleaned, col)
        print(f"Outliers capped for column: {col}")

# Additional Data Validation: Fix logically impossible values
if 'dti' in df_cleaned.columns:
    df_cleaned['dti'] = df_cleaned['dti'].clip(lower=0, upper=100)
if 'annual_inc' in df_cleaned.columns:
    df_cleaned['annual_inc'] = df_cleaned['annual_inc'].clip(lower=0)

Outliers capped for column: loan_amnt
Outliers capped for column: annual_inc
Outliers capped for column: dti

In [11]:
# Save the cleaned DataFrame to a new CSV file
cleaned_file_path = DATA_PATH + 'lending_club_loans_cleaned.csv'
df_cleaned.to_csv(cleaned_file_path, index=False)
print(f"Master cleaned dataset saved successfully to '{cleaned_file_path}'")
print(f"Final Shape: {df_cleaned.shape[0]} rows, {df_cleaned.shape[1]} columns")

Master cleaned dataset saved successfully to '../data/lending_club_loans_cleaned.csv'
Final Shape: 1345350 rows, 90 columns

In [12]:
# Quick sanity check
print("Sample of cleaned data:")
display(df_cleaned.head())
print("\nData types and non-null counts:")
df_cleaned.info()

Sample of cleaned data:

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,3600.00,3600.00,3600.00,36 months,13.99,123.03,C,C4,10+ years,MORTGAGE,55000.00,Not Verified,Dec-2015,Fully Paid,n,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.00,Aug-2003,675.00,679.00,1.00,7.00,0.00,2765.00,29.70,13.00,w,0.00,0.00,4421.72,4421.72,3600.00,821.72,0.00,0.00,0.00,Jan-2019,122.67,Mar-2019,564.00,560.00,0.00,1.00,Individual,0.00,722.00,144904.00,9300.00,4.00,20701.00,1506.00,37.20,0.00,0.00,148.00,128.00,3.00,3.00,1.00,4.00,4.00,2.00,2.00,4.00,2.00,5.00,3.00,4.00,9.00,4.00,7.00,0.00,0.00,0.00,3.00,76.90,0.00,0.00,0.00,178050.00,7746.00,2400.00,13734.00,N,Cash,N
1,24700.00,24700.00,24700.00,36 months,11.99,820.28,C,C1,10+ years,MORTGAGE,65000.00,Not Verified,Dec-2015,Fully Paid,n,small_business,Business,577xx,SD,16.06,1.00,Dec-1999,715.00,719.00,4.00,22.00,0.00,21470.00,19.20,38.00,w,0.00,0.00,25679.66,25679.66,24700.00,979.66,0.00,0.00,0.00,Jun-2016,926.35,Mar-2019,699.00,695.00,0.00,1.00,Individual,0.00,0.00,204396.00,111800.00,4.00,9733.00,57830.00,27.10,0.00,0.00,113.00,192.00,2.00,2.00,4.00,2.00,0.00,0.00,5.00,5.00,13.00,17.00,6.00,20.00,27.00,5.00,22.00,0.00,0.00,0.00,2.00,97.40,7.70,0.00,0.00,314017.00,39475.00,79300.00,24667.00,N,Cash,N
2,20000.00,20000.00,20000.00,60 months,10.78,432.66,B,B4,10+ years,MORTGAGE,63000.00,Not Verified,Dec-2015,Fully Paid,n,home_improvement,Unknown,605xx,IL,10.78,0.00,Aug-2000,695.00,699.00,0.00,6.00,0.00,7869.00,56.20,18.00,w,0.00,0.00,22705.92,22705.92,20000.00,2705.92,0.00,0.00,0.00,Jun-2017,15813.30,Mar-2019,704.00,700.00,0.00,1.00,Joint App,0.00,0.00,189699.00,14000.00,6.00,31617.00,2737.00,55.90,0.00,0.00,125.00,184.00,14.00,14.00,5.00,101.00,10.00,0.00,2.00,3.00,2.00,4.00,6.00,4.00,7.00,3.00,6.00,0.00,0.00,0.00,0.00,100.00,50.00,0.00,0.00,218418.00,18696.00,6200.00,14877.00,N,Cash,N
4,10400.00,10400.00,10400.00,60 months,22.45,289.91,F,F1,3 years,MORTGAGE,104433.00,Source Verified,Dec-2015,Fully Paid,n,major_purchase,Major purchase,174xx,PA,25.37,1.00,Jun-1998,695.00,699.00,3.00,12.00,0.00,21929.00,64.50,35.00,w,0.00,0.00,11740.50,11740.50,10400.00,1340.50,0.00,0.00,0.00,Jul-2016,10128.96,Mar-2018,704.00,700.00,0.00,1.00,Individual,0.00,0.00,331730.00,34000.00,10.00,27644.00,4567.00,77.50,0.00,0.00,128.00,210.00,4.00,4.00,6.00,4.00,1.00,0.00,4.00,6.00,5.00,9.00,10.00,7.00,19.00,6.00,12.00,0.00,0.00,0.00,4.00,96.60,60.00,0.00,0.00,439570.00,95768.00,20300.00,88097.00,N,Cash,N
5,11950.00,11950.00,11950.00,36 months,13.44,405.18,C,C3,4 years,RENT,34000.00,Source Verified,Dec-2015,Fully Paid,n,debt_consolidation,Debt consolidation,300xx,GA,10.20,0.00,Oct-1987,690.00,694.00,0.00,5.00,0.00,8822.00,68.40,6.00,w,0.00,0.00,13708.95,13708.95,11950.00,1758.95,0.00,0.00,0.00,May-2017,7653.56,May-2017,759.00,755.00,0.00,1.00,Individual,0.00,0.00,12798.00,12900.00,0.00,2560.00,844.00,91.00,0.00,0.00,338.00,54.00,32.00,32.00,0.00,36.00,7.00,0.00,2.00,3.00,2.00,2.00,2.00,4.00,4.00,3.00,5.00,0.00,0.00,0.00,0.00,100.00,100.00,0.00,0.00,16900.00,12798.00,9400.00,4000.00,N,Cash,N

Data types and non-null counts:
<class 'pandas.core.frame.DataFrame'>
Index: 1345350 entries, 0 to 2260697
Data columns (total 90 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   loan_amnt                   1345350 non-null  float64
 1   funded_amnt                 1345350 non-null  float64
 2   funded_amnt_inv             1345350 non-null  float64
 3   term                        1345350 non-null  object
 4   int_rate                    1345350 non-null  float64
 5   installment                 1345350 non-null  float64
 6   grade                       1345350 non-null  object
 7   sub_grade                   1345350 non-null  object
 8   emp_length                  1345350 non-null  object
 9   home_ownership              1345350 non-null  object
 10  annual_inc                  1345350 non-null  float64
 11  verification_status         1345350 non-null  object
 12  issue_d                     1345350 non-null  object
 13  loan_status                 1345350 non-null  object
 14  pymnt_plan                  1345350 non-null  object
 15  purpose                     1345350 non-null  object
 16  title                       1345350 non-null  object
 17  zip_code                    1345350 non-null  object
 18  addr_state                  1345350 non-null  object
 19  dti                         1345350 non-null  float64
 20  delinq_2yrs                 1345350 non-null  float64
 21  earliest_cr_line            1345350 non-null  object
 22  fico_range_low              1345350 non-null  float64
 23  fico_range_high             1345350 non-null  float64
 24  inq_last_6mths              1345350 non-null  float64
 25  open_acc                    1345350 non-null  float64
 26  pub_rec                     1345350 non-null  float64
 27  revol_bal                   1345350 non-null  float64
 28  revol_util                  1345350 non-null  float64
 29  total_acc                   1345350 non-null  float64
 30  initial_list_status         1345350 non-null  object
 31  out_prncp                   1345350 non-null  float64
 32  out_prncp_inv               1345350 non-null  float64
 33  total_pymnt                 1345350 non-null  float64
 34  total_pymnt_inv             1345350 non-null  float64
 35  total_rec_prncp             1345350 non-null  float64
 36  total_rec_int               1345350 non-null  float64
 37  total_rec_late_fee          1345350 non-null  float64
 38  recoveries                  1345350 non-null  float64
 39  collection_recovery_fee     1345350 non-null  float64
 40  last_pymnt_d                1345350 non-null  object
 41  last_pymnt_amnt             1345350 non-null  float64
 42  last_credit_pull_d          1345350 non-null  object
 43  last_fico_range_high        1345350 non-null  float64
 44  last_fico_range_low         1345350 non-null  float64
 45  collections_12_mths_ex_med  1345350 non-null  float64
 46  policy_code                 1345350 non-null  float64
 47  application_type            1345350 non-null  object
 48  acc_now_delinq              1345350 non-null  float64
 49  tot_coll_amt                1345350 non-null  float64
 50  tot_cur_bal                 1345350 non-null  float64
 51  total_rev_hi_lim            1345350 non-null  float64
 52  acc_open_past_24mths        1345350 non-null  float64
 53  avg_cur_bal                 1345350 non-null  float64
 54  bc_open_to_buy              1345350 non-null  float64
 55  bc_util                     1345350 non-null  float64
 56  chargeoff_within_12_mths    1345350 non-null  float64
 57  delinq_amnt                 1345350 non-null  float64
 58  mo_sin_old_il_acct          1345350 non-null  float64
 59  mo_sin_old_rev_tl_op        1345350 non-null  float64
 60  mo_sin_rcnt_rev_tl_op       1345350 non-null  float64
 61  mo_sin_rcnt_tl              1345350 non-null  float64
 62  mort_acc                    1345350 non-null  float64
 63  mths_since_recent_bc        1345350 non-null  float64
 64  mths_since_recent_inq       1345350 non-null  float64
 65  num_accts_ever_120_pd       1345350 non-null  float64
 66  num_actv_bc_tl              1345350 non-null  float64
 67  num_actv_rev_tl             1345350 non-null  float64
 68  num_bc_sats                 1345350 non-null  float64
 69  num_bc_tl                   1345350 non-null  float64
 70  num_il_tl                   1345350 non-null  float64
 71  num_op_rev_tl               1345350 non-null  float64
 72  num_rev_accts               1345350 non-null  float64
 73  num_rev_tl_bal_gt_0         1345350 non-null  float64
 74  num_sats                    1345350 non-null  float64
 75  num_tl_120dpd_2m            1345350 non-null  float64
 76  num_tl_30dpd                1345350 non-null  float64
 77  num_tl_90g_dpd_24m          1345350 non-null  float64
 78  num_tl_op_past_12m          1345350 non-null  float64
 79  pct_tl_nvr_dlq              1345350 non-null  float64
 80  percent_bc_gt_75            1345350 non-null  float64
 81  pub_rec_bankruptcies        1345350 non-null  float64
 82  tax_liens                   1345350 non-null  float64
 83  tot_hi_cred_lim             1345350 non-null  float64
 84  total_bal_ex_mort           1345350 non-null  float64
 85  total_bc_limit              1345350 non-null  float64
 86  total_il_high_credit_limit  1345350 non-null  float64
 87  hardship_flag               1345350 non-null  object
 88  disbursement_method         1345350 non-null  object
 89  debt_settlement_flag        1345350 non-null  object
dtypes: float64(69), object(21)
memory usage: 934.0+ MB